use project_01

--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer_table
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount 
from customer_table
where  discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer_table)
--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased , round(avg (review_rating),2) as "Average_product_rating"
from customer_table
group by item_purchased
order by (Average_product_rating) desc
offset 0 rows fetch next 5 rows only;
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount),0)
from customer_table
where shipping_type in ('Express','Standard')
group by shipping_type ;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,  round(avg(purchase_amount),2) as 'who',
count(customer_id)  as 'total customer',
sum(purchase_amount) as 'total'
from customer_table
group by subscription_status
order by total  asc;
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100*sum(case when  discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as Discount_rate
from customer_table
group by item_purchased
order by Discount_rate desc
offset 0 rows fetch next 5 rows only;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment.
with customer_type as(
select previous_purchases, customer_id,
case
    when previous_purchases = 1 then 'New'
    when previous_purchases  between 2 and 10 then 'Returning'
    else 'loyal'
    end as customer_segment 
from customer_table
)
select  customer_segment, count(*) as 'Number_of_customer'
from customer_type
group by customer_segment
order by Number_of_customer desc;

--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders, 
row_number()over(partition by category order by count(customer_id) desc) as  item_rank
from customer_table 
group by category,item_purchased)
select item_rank, category , item_purchased,total_orders
from item_counts 
where item_rank <= 3;
select * from customer_table;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_table
where previous_purchases >5
group by subscription_status
order by repeat_buyers desc;

 --Q10. What is the rvenue contribution of each age group?
 select age_group, 
 sum(purchase_amount) as total_revenue
 from customer_table
 group by age_group 
 order by total_revenue desc;

 select * from customer_table;


















